services:
  - type: web
    name: dhiraj-my-portfolio-api
    runtime: buildpack   # ✅ Correct runtime for Spring Boot
    plan: free
    buildCommand: "./mvnw clean install -DskipTests"   # ✅ Use Maven Wrapper
    startCommand: "java -jar target/My-Portfolio-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: "jdbc:postgresql://dpg-d2md3nbuibrs73eu34l0-a.oregon-postgres.render.com:5432/portfolio_db_543c"
      - key: DB_USER
        value: "portfolio_db_543c_user"
      - key: DB_PASSWORD
        value: "JpBZr9V6Xxyg7a3LCMxydbqgNaSNqoyE"
      - key: JWT_SECRET
        value: "M2Q2MjJjODAwOWY1MDhmNmUwNDhiMzY3YzI5NTYxNjA2MWViYjUyNTV1OTgyZTcyMjYw"
    autoDeploy: true
