services:
  - type: web
    name: dhiraj-my-portfolio-api
    runtime: docker              # ✅ Correct since you’re using a Dockerfile
    plan: free
    dockerfilePath: ./Dockerfile # ✅ Points to Dockerfile in repo root
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://dpg-d2md3nbuibrs73eu34l0-a.oregon-postgres.render.com:5432/portfolio_db_543c"
      - key: SPRING_DATASOURCE_USERNAME
        value: "portfolio_db_543c_user"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "JpBZr9V6Xxyg7a3LCMxydbqgNaSNqoyE"
      - key: JWT_SECRET
        value: "M2Q2MjJjODAwOWY1MDhmNmUwNDhiMzY3YzI5NTYxNjA2MWViYjUyNTV1OTgyZTcyMjYw"
    autoDeploy: true
