# File: render.yaml
services:
  - type: web
    name: dhiraj-my-portfolio-api
    env: java # Explicitly specify the environment as Java
    plan: free
    buildCommand: "mvn clean install"
    startCommand: "java -jar target/My-Portfolio-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: "jdbc:postgresql://your-host.render.com:5432/your-db"
      - key: DB_USER
        value: "your_database_username"
      - key: DB_PASSWORD
        value: "your_database_password"
      - key: JWT_SECRET
        value: "a-very-long-and-random-string"
    autoDeploy: true
